name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: '10.17.0'
          
      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV
          
      - name: Setup pnpm cache
        uses: actions/cache@v4
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-
            
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
        
      - name: Type check
        run: pnpm run check-types
        
      - name: Format check
        run: pnpm run format:check
        
      - name: Run unit tests
        run: pnpm run test:unit
        
      - name: Run Storybook tests
        run: pnpm run test:storybook
        working-directory: packages/ui
        
      - name: Build Storybook
        run: pnpm run build-storybook
        working-directory: packages/ui
        
      - name: Generate coverage report
        run: pnpm run test:coverage
        
      # Coverage upload disabled - keeping local only
      # - name: Upload test coverage
      #   uses: codecov/codecov-action@v4
      #   if: always()
      #   with:
      #     files: ./packages/ui/coverage/lcov.info
      #     fail_ci_if_error: false